services:
  web:
    # image: "streamlit"
    build: .
    ports:
      - 8501:8501
    volumes:
      - .:/app
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
